include: package:lints/recommended.yaml

formatter:
  page_width: 100

analyzer:
  plugins:

linter:
  rules:
  - prefer_single_quotes
  - always_declare_return_types
  - public_member_api_docs
  - always_put_control_body_on_new_line
  - await_only_futures
  - cascade_invocations
  - combinators_ordering
  - require_trailing_commas
  - flutter_style_todos
  - library_annotations
  - missing_whitespace_between_adjacent_strings
  - prefer_foreach
  - unawaited_futures
  - unnecessary_breaks
  - unnecessary_lambdas
  - unnecessary_parenthesis
  - use_enums
  - sort_pub_dependencies

